### ISSUE TITLE
Specify dependency on pulumi-docker in schema for Multi Language

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-awsx#742]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

For MLC support, AFAICT, the internal implementation of the provider depends on `pulumi-docker` (e.g. for [ECS](https://github.com/pulumi/pulumi-awsx/pull/734)), but this dependency is not specified in the schema for any of the languages, which will prevent plugin discovery from working correctly.

Note: When the AWSX plugin is initially installed, I would expect the Pulumi `docker` plugin to be installed as part of installing the AWSX plugin's NPM dependencies (i.e. installing `@pulumi/docker` will end up running `pulumi plugin install resource docker ...`). However, if someone deletes the `docker` plugin from their machine, and is using AWSX from Python, .NET, or Go, the next time they run `pulumi up`, it won't statically be able to determine that `docker` is a required plugin, so it won't be installed automatically.

For Python and .NET, the fix is to specify a dependency on `pulumi-docker` and `Pulumi.Docker` in the schema:

https://github.com/pulumi/pulumi-awsx/blob/69254186707fd9c1108c4c758a8db136be35d3c9/provider/cmd/pulumi-resource-awsx/schema.json#L164-L167

https://github.com/pulumi/pulumi-awsx/blob/69254186707fd9c1108c4c758a8db136be35d3c9/provider/cmd/pulumi-resource-awsx/schema.json#L151-L154

For Go, dependencies are specified manually in the Go SDK's `go.mod` (the `go.mod` file is not generated automatically). However, when manually specifying a dependency on `github.com/pulumi/pulumi-docker/sdk/v3` in the `go.mod`, if it's not actually being used in the Go SDK, it'll be removed by `go mod tidy`. https://github.com/pulumi/pulumi/issues/9180 tracks adding a way to specify Go dependencies in the schema, which will generate some dummy imports inside the generated Go SDK, so such dependencies won't be stripped from `go.mod` by `go mod tidy`.

## Tasks

- [ ] Python: Specify dependency on `pulumi-docker` in schema
- [ ] .NET: Specify dependency on `Pulumi.Docker` in schema
- [ ] Go: Specify dependency on docker (blocked on https://github.com/pulumi/pulumi/issues/9180)
